version: '3'

services:
  server:
    image: node:12.14.0
    working_dir: /home/app/server
    command: yarn start
    ports:
      - 3000:3000
    volumes:
      - .:/home/app
      - server_node_modules:/home/app/server/node_modules

  client:
    image: node:12.14.0
    working_dir: /home/app/client
    command: yarn watch
    volumes:
      - ./client:/home/app/client
      - client_node_modules:/home/app/client/node_modules
    depends_on:
      - server

volumes:
  server_node_modules:
  client_node_modules:

